version: "3"

services:
  web:
    image: php:8.2-apache
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    command: >
      bash -c "
        sed -ri -e 's!/var/www/html!$${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf &&
        sed -ri -e 's!/var/www/!$${APACHE_DOCUMENT_ROOT}/!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf &&
        a2enmod rewrite &&
        apache2-foreground
      "
    restart: unless-stopped
