version: "3"

services:
  web:
    image: php:8.2-apache
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    command: >
      bash -c "
        sed -ri -e 's!/var/www/html!$${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf &&
        sed -ri -e 's!/var/www/!$${APACHE_DOCUMENT_ROOT}/!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf &&
        sed -ri -e 's!upload_max_filesize = 2M!upload_max_filesize = 100M!g' /usr/local/etc/php/php.ini-production &&
        sed -ri -e 's!post_max_size = 8M!post_max_size = 100M!g' /usr/local/etc/php/php.ini-production &&
        cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini &&
        a2enmod rewrite &&
        a2enmod dump_io &&
        apache2-foreground
      "
    restart: unless-stopped
# service apache2 --full-restart
# a2enmod dump_io
# apt-get update
# apt-get install -y nano
# Add this in the site-available/000-default.conf file to enable the dump_io module
#  DumpIOInput On
#  DumpIOOutput On
#  LogLevel dumpio:trace7

